name: Port Jira Integration

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  port-jira-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Add Port Helm Repository
        run: |
          helm repo add port-labs https://port-labs.github.io/helm-charts
          helm repo update

      - name: Setup Port Jira Integration
        run: |
          helm upgrade --install jira port-labs/port-ocean \
          --set port.clientId="E8b9n9qlbbd5js1nLLHQG7i5LVSQvXyQ" \
          --set port.clientSecret="ON3rvb4Xtdn6pgapQmGVZPfAVX1Znfd3Xy1lbrI4k6YlzeXR4m4SBdLGyiBPhX" \
          --set port.baseUrl="https://api.port.io" \
          --set initializePortResources=true \
          --set integration.identifier="jira" \
          --set integration.type="jira" \
          --set integration.eventListener.type="POLLING" \
          --set integration.config.jiraHost="${{ secrets.JIRAHOST }}" \
          --set integration.secrets.atlassianUserEmail="${{ secrets.ATLASSIANUSEREMAIL }}" \
          --set integration.secrets.atlassianUserToken="${{ secrets.ATLASSIANUSERTOKEN }}"
