name: Port Jira Integration

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-port-jira:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Add Port Helm Repository
        run: |
          helm repo add --force-update port-labs https://port-labs.github.io/helm-charts
          helm repo update

      - name: Deploy Port Ocean Jira Integration
        run: |
          helm upgrade --install jira port-labs/port-ocean \
            --set port.clientId="E8b9n9qlbbd5js1nLLHQG7i5LVSQvXyQ" \
            --set port.clientSecret="ON3rvb4Xtdn6pgapQmGVZPfAVX1Znfd3Xy1lbrI4k6YlzeXR4m4SBdLGyiBPhX" \
            --set port.baseUrl="https://api.port.io" \
            --set initializePortResources=true \
            --set integration.identifier="jira" \
            --set integration.type="jira" \
            --set integration.config.jiraHost="${{ secrets.jiraHost }}" \
            --set integration.config.jql="project = YourProjectKey" \
            --set integration.secrets.atlassianUserEmail="${{ secrets.atlassianUserEmail }}" \
            --set integration.secrets.atlassianUserToken="${{ secrets.atlassianUserToken }}"
